### PR TITLE
added more error configurations to give users meaningful error message

### PR DESCRIPTION
**Pull request by Aswanth-c**
fixed mentioned issue https://github.com/modularcloud/explorer/issues/119

### CODE REVIEW

**Review by rubyanddiamond — APPROVED** [review]
Approve for now and let’s further review copywriting with another PR later if we run into errors needing better explanation.

**Review by pynchmeister — CHANGES_REQUESTED** [review]
Addresses @rubyanddiamond comment regarding correct files but incorrect address, but does not address the instance where the user provides some but not all of the required files (for example, the user provides a .json file but not a .sol file). In this case the error message shows 'Contract Not Verified", when it would be more appropriate to say: "All required files were not provided".

**Comment by Aswanth-c** [comment]
> Addresses @rubyanddiamond comment regarding correct files but incorrect address, but does not address the instance where the user provides some but not all of the required files (for example, the user provides a .json file but not a .sol file). In this case the error message shows 'Contract Not Verified", when it would be more appropriate to say: "All required files were not provided".

I think I already fixed those issue,  it will be great if you can provide me an  example 
because if the user is missing a metadata json file it will respond with this and
Screenshot 2023-08-21 at 11 57 25 PM
(nvm the black theme I have an extension that makes all Website darker)
If the user is  missing any solidity files it will respond with this
Screenshot 2023-08-21 at 11 57 00 PM

**Comment by pynchmeister** [comment]
## Summary of Requested Changes

(If there are any desired browsers not listed here let me know)

Drag and drop is not functional on any browsers.

### Safari

Here is an example of the aforementioned issue. Despite the contract being verified, the response should be more verbose as to say "All required files are not included and the contract is already verified" or something to that effect.

Screenshot 2023-08-22 at 3 09 13 PM

Also drag and drop is not working (on Safari)

### Firefox

> Despite the contract being verified, the response should be more verbose as to say "All required files are not included and the contract is already verified" or something to that effect.

This issue is also occurring on Firefox. I think a good way to structure the responses would be to inform the user of which file they are missing. For example: "Only the .sol (or .json) is included, please add the remaining file.

When I changed the address by one character (to be incorrect) and added only the .sol file, I got the response: "Verification Failed Metadata file not found. Did you include metadata.json"?

I think this would be better phrased as to inform the user that their address is incorrect, and we could change the response to "Verification failed. JSON file not found. Did you include the JSON file?".

### Chrome

> Despite the contract being verified, the response should be more verbose as to say "All required files are not included and the contract is already verified" or something to that effect.

This issue is also occurring on Chrome. I think a good way to structure the responses would be to inform the user of which file they are missing. For example: "Only the .sol (or .json) is included, please add the remaining file.

When I changed the address by one character (to be incorrect) and added only the .json file, I got the response: "Verification Failed Resource missing; unsuccessful fetching: HelloWorld.sol".

This would be better phrased as follows: "Verification failed; Solidity file missing."

The Firefox suggestion regarding the provision of the Solidity file but not the JSON file applies here as well.

### Arc

The aforementioned bug with only one of the two necessary files included applies here. As well as the bug with the change to an incorrect address.

### Brave

> The aforementioned bug with only one of the two necessary files included applies here. As well as the bug with the change to an incorrect address.

**Comment by Aswanth-c** [comment]
> ## Summary of Requested Changes
> (If there are any desired browsers not listed here let me know)
> 
> Drag and drop is not functional on any browsers.
> 
> ### Safari
> Here is an example of the aforementioned issue. Despite the contract being verified, the response should be more verbose as to say "All required files are not included and the contract is already verified" or something to that effect.
> 
> Screenshot 2023-08-22 at 3 09 13 PM
> Also drag and drop is not working (on Safari)
> 
> ### Firefox
> > Despite the contract being verified, the response should be more verbose as to say "All required files are not included and the contract is already verified" or something to that effect.
> 
> This issue is also occurring on Firefox. I think a good way to structure the responses would be to inform the user of which file they are missing. For example: "Only the .sol (or .json) is included, please add the remaining file.
> 
> When I changed the address by one character (to be incorrect) and added only the .sol file, I got the response: "Verification Failed Metadata file not found. Did you include metadata.json"?
> 
> I think this would be better phrased as to inform the user that their address is incorrect, and we could change the response to "Verification failed. JSON file not found. Did you include the JSON file?".
> 
> ### Chrome
> > Despite the contract being verified, the response should be more verbose as to say "All required files are not included and the contract is already verified" or something to that effect.
> 
> This issue is also occurring on Chrome. I think a good way to structure the responses would be to inform the user of which file they are missing. For example: "Only the .sol (or .json) is included, please add the remaining file.
> 
> When I changed the address by one character (to be incorrect) and added only the .json file, I got the response: "Verification Failed Resource missing; unsuccessful fetching: HelloWorld.sol".
> 
> This would be better phrased as follows: "Verification failed; Solidity file missing."
> 
> The Firefox suggestion regarding the provision of the Solidity file but not the JSON file applies here as well.
> 
> ### Arc
> The aforementioned bug with only one of the two necessary files included applies here. As well as the bug with the change to an incorrect address.
> 
> ### Brave
> > The aforementioned bug with only one of the two necessary files included applies here. As well as the bug with the change to an incorrect address.

I think you mistaken drag and drop pr to this pr 
It's a different pr and it has already been merged 

>All required files are not included and the contract is already verified

If the contract is already verified it doesn't matter what files they added or not I can change it to 
"This contract address has been already verified then link to the respective files"

> When I changed the address by one character (to be incorrect) and added only the .sol file, I got the response: "Verification Failed Metadata file not found. Did you include metadata.json"?

> I think this would be better phrased as to inform the user that their address is incorrect, and we could change the response to "Verification failed. JSON file not found. Did you include the JSON file?".

sourcify doesn't start verification until we provide metadata.json hence we won't be able to know beforehand if the contract address is valid or not.

if you add a metadata.json  it  will display the  error message stating that the contract address is invalid

**Review by pynchmeister — APPROVED** [review]

**Comment by pynchmeister** [comment]
> I think you mistaken drag and drop pr to this pr
It's a different pr and it has already been merged

Understood, my mistake. Thanks for addressing my concerns; approved.

**Comment by Aswanth-c** [comment]
> 

No worries merging it now

**Pull request merged**
